### ISSUE TITLE
クラウドのPCの状態確認

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_maintenance#1]
本日の作業をお願いしようとリモートにアクセスしたところ
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/f4222867-003c-458a-b70a-c7b93ff2c0f4)
isupport_remoteが接続しても画面真っ黒です。
一度ご確認ください。
その他は動きます。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/c9213740-c072-4906-b3e4-72e4c824544d)

**Comment by nagasawajun** [comment]
確認しますので、少しお時間ください。
本日、Pマークの外部監査が行われており、画面のモニタを切ったことが影響しているのかもしれません。

**Comment by city-soja-chiiki** [comment]
了解しました。
作業は月曜日に行います。

**Comment by nagasawajun** [comment]
モニタ付けました。SOJA01で画面が表示されることを確認しましたので、お手数ですがご確認お願いいたします。

**Comment by yamamoto-ryuzo** [comment]
確認しました。
でも，そんな設定悲しいことなので仮想モニタドライバないか確認したらありました。
https://help.rview.com/hc/ja/articles/10839037150355-%E6%8E%A5%E7%B6%9A%E5%85%88PC%E3%81%AE%E3%83%A2%E3%83%8B%E3%82%BF%E3%83%BC%E3%81%8C%E8%AA%8D%E8%AD%98%E3%81%95%E3%82%8C%E3%81%9A-%E9%81%A0%E9%9A%94%E6%8E%A5%E7%B6%9A%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84%E5%A0%B4%E5%90%88
モニタ電源もったいないので，一度切ってご確認ください。

**Comment by nagasawajun** [comment]
情報ありがとうございます。週末に試してみます。また、結果ご報告いたします。

**Comment by yamamoto-ryuzo** [comment]
ドライバーはインストール済みです。
また、その他のハイパーV環境はもともと仮想なので影響を受けていません。
念のため。

**Comment by nagasawajun** [comment]
ありがとうございます。
isupport_remote
がモニタを切った状態で画面表示されることを確認できました。
以後、モニタを切った状態にしておきます。

**Comment by yamamoto-ryuzo** [comment]
こちらでも確認しました。
日曜日にお疲れ様です。
