### ISSUE TITLE
作業手順を整備しました

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_maintenance#2]
概ねの作業手順を整備しました。
解らなければISUUESに御願いします。
結果をREADMEに順次追記してゆきます。

地域応援課作成のファイルは
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/09bc1232-6441-4afe-a08d-bc751bf5f986)
に置いておきました。

2023道路パトロール.gpkg　です。
作業が完了したら削除してください。

**Comment by nagasawajun** [comment]
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110758944/bb41a21b-6d74-4935-8f70-9262f7631d3b)

**Comment by nagasawajun** [comment]
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110758944/0727da37-45ed-406d-85d1-7b16ee509f90)

**Comment by isupport-kitta** [comment]
お世話になります。道路パトロール作業用レイヤを編集（消去日及び取得日入力）をしてプロセシングツールでPostGISへエクスポートしようと試みたところ以下のエラーが出てしまいました。原因を調べましたが不明です。また対処方法などわかりましたらお知らせいただけると幸いです。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110583661/c30338be-3a85-4edd-ac0a-0aa9aa40e089)

**Comment by yamamoto-ryuzo** [comment]
下記のGDALによるPostgreSQL出力を使用してください。
ポータブル版のQGISのPython設定がいまいちだったので，インストール版で対応しました。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/50c5f188-c405-4e92-a4e0-32fa90c5d944)

**Comment by yamamoto-ryuzo** [comment]
追加作業で，下記２作業が必要でした・・・
出来るようならやってみてください。
このあたりの設定変更は今後QGISの表示管理で必須になる項目です。

https://github.com/city-soja-chiiki/douro_maintenance/issues/5
https://github.com/city-soja-chiiki/douro_maintenance/issues/6

**Comment by isupport-kitta** [comment]
> 下記のGDALによるPostgreSQL出力を使用してください。ポータブル版の QGISのPython設定があったため、インストール版で対応しました。 ![画像](https://user-images.githubusercontent.com/86514652/252225215-50c5f188-c405-4e92-a4e0-32fa90c5d944.png)

こちらを実行したのですがトラックバックがでてしまいます。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110583661/72531995-e268-4c7b-a3f7-4a3b5271f80d)

何か設定等で足りない箇所があるのでしょうか

**Comment by yamamoto-ryuzo** [comment]
## これ3.22を独自にインストールしたQGISから動作させました？
　↑　一番重要！！！


総社市が設置しているポータブル版は，いろいろなパスが結構いい加減なので，複雑な作業でエラーが出ます。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/67f5f80a-5c2d-4a83-ad0b-68b030db2985)
にしても，Pythonのパス設定が気に入らないような？
もしくは，ジオメトリ型とマルチポリゴンに指定するとか・・・
曖昧なの表現を少なくするとエラーも少なくなります。

**Comment by isupport-kitta** [comment]
> 
"\\soja\総社市\QGIS\yr-qgis-portable-launcher3.22.16\QGIS3.22.16.bat"から起動したQGISを使用していました。

QGIS3.22を起動して"\\soja\総社市\道路・水路台帳システム\chiiki-iji\road_maintenance.qgs"を開きました。
やはりエラーが出てしまいます。

**Comment by nagasawajun** [comment]
山本様

申し訳ございません。私と橘田で試しているのですがうまくいきません。
明日朝一、ZOOMにて画面で見ていただくことは可能でしょうか。
ZOOMURLはsuidou@の方にメールいたします。

**Comment by yamamoto-ryuzo** [comment]
お疲れ様です。
これは接続できていません・・・
「lizmap」です！小文字にしてください。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/c272710a-7d55-4b2d-8933-ef2c0b0f68a1)
大文字の「LIZMAP」になってます。

**Comment by yamamoto-ryuzo** [comment]
ちなみに、データベースは私がすでに更新済みなのでそんなに急ぐ必要ないと思います。
ただし、設定変更してもらったｑｇｓ+ｑｇｓ.ｃｆｇのFTP転送は必要です。
いずれにせよ、もう遅いので明日一番で！

**Comment by yamamoto-ryuzo** [comment]
あ！ネットワークのパスワードも張り付いていたので画像は削除しました。
データベースの利用時はセキュリティーにも気を付けてください。
情報を埋め込んでいるので。

**Comment by nagasawajun** [comment]
ありがとうございます。明日一番お願いいたします。
