### ISSUE TITLE
表示状態の修正

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_maintenance#3]
消去日がNULLに対応していませんでしたので。
修正しました。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/234388b1-9fb6-43c8-8d2a-c8b953eb10e7)
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/519b7bf8-aa8b-4cb4-b5b2-2dcf876aba03)

もんだい問題なければ一週間程度でクローズします。

**Comment by yamamoto-ryuzo** [comment]
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/55fa00f9-c5a7-477a-959a-4e62181762bf)
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/4ba5b760-1bb8-49a0-b07b-e8ce227600f9)
に修正しました。

また，ラベルの表示を下記に見直しました。
その他，ラベルの表示設定も強制表示等見直しています。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/4513dee0-07b9-4363-b24d-66b56c8c39c1)

**Comment by isupport-kitta** [comment]
@dayを7/11に設定すると注記が二重に出るようになってしまいました。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110583661/4fa180f6-5857-4931-a86f-38114a9d7f97)

**Comment by yamamoto-ryuzo** [comment]
これは，道路パトロールを表示しているからでは？

**Comment by isupport-kitta** [comment]
> これは，道路パトロールを表示しているからでは？

道路パトロールを非表示にしたら直りました。すいません。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110583661/686f9b6a-20eb-4efa-ac25-09accf541a84)

**Comment by yamamoto-ryuzo** [comment]
私の条件式が間違っていたようです。
ＡＮＤ　ＯＲ　に換えました。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/32c7a4f7-e65f-492e-8908-c6c1ae4b02db)
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/3d7b5d10-b7ab-4e51-b639-1875b6439325)
