### ISSUE TITLE
シンボルの追加

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_maintenance#5]
新しいエリアのシンボル追加可能でしょうか。
可能ならやってみてください。
困難な場合はこちらで行います。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/c787e533-799b-42d4-b204-c2a79b1c3270)

**Comment by isupport-kitta** [comment]
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110583661/1a3c792f-2eb8-493a-b436-8e7604c6cf83)
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110583661/fd9a7063-1d0d-42d3-be51-7fc8e9af0389)
こんな感じでよろしかったでしょうか。

**Comment by yamamoto-ryuzo** [comment]
ナイスです！
