### ISSUE TITLE
フォームのバリューマップの追加

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [city-soja-chiiki/douro_maintenance#6]
新しいエリアのバリューマップ追加可能でしょうか。
可能ならやってみてください。
困難な場合はこちらで行います。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/86514652/37a940bc-0bf8-4ef9-86f4-0fb96af002d1)

**Comment by isupport-kitta** [comment]
バリューマップの値を追加しました。
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110583661/7568b1d7-e0cc-40cb-bcff-af0849ed2fad)

**Comment by yamamoto-ryuzo** [comment]
出来たら，Ｍの続きにＮ，Ｏ，Ｐ，Ｑを入れてやってください。
ＬＩＺＭＡＰで選択するときにその順番になると思うので。

**Comment by isupport-kitta** [comment]
![image](https://github.com/city-soja-chiiki/douro_maintenance/assets/110583661/b3742963-b301-40c3-b676-97fd8b570ae4)
修正しました。

**Comment by yamamoto-ryuzo** [comment]
ありがとうございます。
